name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.0
        with:
          directory: ../../src
